# spark-preprocessing/config.properties
# Ces chemins correspondent aux montages dans le container Docker.
# Ils peuvent être surchargés par les variables d'environnement
# définies dans docker-compose.yml (priorité sur ce fichier).

path.train.in=/data/raw/train
path.test.in=/data/raw/test
path.train.out=/data/processed/train
path.test.out=/data/processed/test
